#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Running linters..."

bundle exec rubocop

echo "==> Running tests..."

if [ -n "$1" ]; then
  # TODO: figure out whether to pass to `rspec` or `ember test`
  # pass arguments to test call. This is useful for calling a single test.
  bundle exec rspec "$1"
else
  bundle exec rspec
  ( cd frontend && ember test )
fi
